name: Sudoku
main: com.comze_instancelabs.sudoku.Main
version: 1.0
author: instancelabs
permissions:
  sudoku.create:
    description: Gives access to create an arena.
commands:
   sudoku:
      description: Main command
      aliases: [su]     
      usage: /<command>
